# Generated by Django 4.2 on 2023-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobileNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
