# Generated by Django 4.2 on 2023-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_member_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='firstName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
