# Generated by Django 4.2 on 2023-09-09 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_member_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthDay',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='member',
            name='father',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('other', 'other')], default='M', max_length=9),
        ),
        migrations.AddField(
            model_name='member',
            name='jobOrg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='kidsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='maritalStatus',
            field=models.BooleanField(default=False),
        ),
    ]
