# Generated by Django 4.2 on 2023-09-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_member_birthday_member_father_member_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='father',
            field=models.ForeignKey(default='USER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='mother',
            field=models.ForeignKey(default='USER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
