# Generated by Django 4.2 on 2023-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_alter_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobileNo',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
