# Generated by Django 4.2 on 2023-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_alter_member_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='maritalStatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
