# Generated by Django 4.2 on 2023-09-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0010_alter_member_maritalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('other', 'other')], default='M', max_length=9),
        ),
    ]
