# Generated by Django 4.2 on 2023-09-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_member_photo2_member_photo3_remove_member_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='member',
            name='father',
        ),
        migrations.AddField(
            model_name='member',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
