# Generated by Django 4.2 on 2023-09-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0013_member_kids_remove_member_father_member_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='kids',
        ),
    ]
