# Generated by Django 4.2 on 2023-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0014_remove_member_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=100, max_digits=9),
        ),
        migrations.AddField(
            model_name='member',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, default=100, max_digits=9),
        ),
        migrations.AddField(
            model_name='member',
            name='pinCode',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
