# Generated by Django 4.2 on 2023-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0015_member_lat_member_lng_member_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='member',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobileNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pinCode',
            field=models.IntegerField(blank=True),
        ),
    ]
