# Generated by Django 4.2 on 2023-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0018_alter_member_father_alter_member_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='book',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Teen', 'Tenn'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Mystery', 'Mystery'), ('History', 'History'), ('Romance', 'Romance'), ('Self Help', 'Self Help'), ('Horror', 'Horror'), ('Crime', 'Crime')], default='Action', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='movie',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Autobiography', 'Autobiography'), ('Comedy', 'Comedy'), ('History', 'History'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Horror', 'Horror'), ('Animation', 'Animation'), ('Adventure', 'Adventure')], default='Crime', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='present',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='sport',
            field=models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Cricket', 'Cricket'), ('TT', 'TT'), ('Tennis', 'Tennis'), ('Volley Ball', 'Volley Ball'), ('Baseball', 'Baseball'), ('Carrom', 'Carrom')], default='Football', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('other', 'other')], default='Male', max_length=9),
        ),
    ]
