# Generated by Django 4.2 on 2023-09-13 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0019_member_book_member_movie_member_present_member_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='++', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='book',
            field=models.CharField(blank=True, choices=[('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Teen', 'Tenn'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Mystery', 'Mystery'), ('History', 'History'), ('Romance', 'Romance'), ('Self Help', 'Self Help'), ('Horror', 'Horror'), ('Crime', 'Crime')], max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='movie',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Autobiography', 'Autobiography'), ('Comedy', 'Comedy'), ('History', 'History'), ('Romance', 'Romance'), ('Crime', 'Crime'), ('Horror', 'Horror'), ('Animation', 'Animation'), ('Adventure', 'Adventure')], max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='sport',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Cricket', 'Cricket'), ('TT', 'TT'), ('Tennis', 'Tennis'), ('Volley Ball', 'Volley Ball'), ('Baseball', 'Baseball'), ('Carrom', 'Carrom')], max_length=15),
        ),
    ]
