# Generated by Django 4.1.4 on 2023-10-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0020_member_spouse_alter_member_book_alter_member_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='book',
            field=models.CharField(blank=True, choices=[('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Teen', 'Teen'), ('Fiction', 'Fiction'), ('Autobiography', 'Autobiography'), ('Mystery', 'Mystery'), ('History', 'History'), ('Romance', 'Romance'), ('Self Help', 'Self Help'), ('Horror', 'Horror'), ('Crime', 'Crime')], max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=9),
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
