# Generated by Django 4.2 on 2023-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0021_game_alter_member_book_alter_member_gender_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Sikh', 'Sikh'), ('Christian', 'Christian')], default='Islam', max_length=20),
        ),
    ]
