# Generated by Django 4.2 on 2023-10-14 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0022_family_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=9),
        ),
        migrations.AlterField(
            model_name='member',
            name='sport',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Badminton', 'Badminton'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Cricket', 'Cricket'), ('TT', 'TT'), ('Tennis', 'Tennis'), ('Volley Ball', 'Volley Ball'), ('Baseball', 'Baseball'), ('Carrom', 'Carrom')], max_length=15),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='family.room')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
