# Generated by Django 4.2 on 2024-01-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0024_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='middleName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
